"""Add provider location sharing

Revision ID: 7d4af6941981
Revises: f4424fe2f02d
Create Date: 2026-10-02 17:40:11.907680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4af6941981'
down_revision = 'f4424fe2f02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'show_location',
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_profiles', schema=None) as batch_op:
        batch_op.drop_column('show_location')

    # ### end Alembic commands ###
